export default {
  REACT_APP_ENV: process.env.REACT_APP_ENV,
  REACT_APP_FEATURE_ADMIN: process.env.REACT_APP_FEATURE_ADMIN === 'true',
  REACT_APP_FEATURE_ANIMATIONS: process.env.REACT_APP_FEATURE_ANIMATIONS === 'true',
  REACT_APP_FEATURE_EDIT_MODE: process.env.REACT_APP_FEATURE_EDIT_MODE === 'true',
  REACT_APP_THEME_PRIMARY: process.env.REACT_APP_THEME_PRIMARY || 'Empty',
  REACT_APP_THEME_SECONDARY: process.env.REACT_APP_THEME_SECONDARY || 'Empty',
  REACT_APP_THEME_TERTIARY: process.env.REACT_APP_THEME_TERTIARY || 'Empty',
  REACT_APP_PERF_MAX_NODES: parseInt(process.env.REACT_APP_PERF_MAX_NODES) || 50,
  REACT_APP_PERF_MONITORING: process.env.REACT_APP_PERF_MONITORING === 'true'
};
